apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: web-rs-s1
  namespace: stage1
  labels:
    tier: web-rs-s1
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: web-rs-s1
  template:
    metadata:
      labels:
        tier: web-rs-s1
    spec:
      containers:
        - name: webservice
          image: raghudevops32/s1-webservice:latest
          ports:
            - containerPort: 80
