---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: rbac
  name: 02-pod-creator
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list", "edit", "create"]
...

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: 02-role-bind
  namespace: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io 
  kind: Role
  name: 02-pod-creator
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: raju

