kind: Pod
apiVersion: v1
metadata:
  name: sample
spec:
  containers:
    - name: nginx
      image:  nginx
      resources:
        requests:
          memory: "1Gi"
          cpu: "50m"
        limits:
          memory: "10Gi"
          cpu: "500m"
