---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: web02-rs
  namespace: demo02
  labels:
    tier: web02-rs
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: web02-rs
  template:
    metadata:
      labels:
        tier: web02-rs
    spec:
      containers:
        - name: webservice
          image: raghudevops32/nw-web02:latest
          ports:
            - containerPort: 80
...

---
kind: Service
apiVersion: v1
metadata:
  namespace: demo02
  name: web02-svc
spec:
  #type: LoadBalancer  
  selector:
    tier: web02-rs
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80