apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
  - name: mycontainer
    image: raghudevops32/studentapp:v3 
    env:
      - name: DBUSERNAME
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: dbusername
      - name: DBPASSWORD
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: dbpassword
