apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stack.fullname" . }}-rs
  labels:
    tier: {{ .Values.names.tier }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      tier: {{ .Values.names.tier }}
  template:
    metadata:
      labels:
        tier: {{ .Values.names.tier }}
    spec:
      containers:
        - name: "tomcat"
          image: "{{ .Values.image.repository }}:{{.Values.image.tag}}"
          ports:
            - containerPort: {{ .Values.service.targerPort }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
