apiVersion: v1
kind: Pod
metadata:
  name: mariadb-pd
spec:
  containers:
  - image: mariadb
    name: mariadb
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: kube-mariadb
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "root"
  volumes:
  - name: kube-mariadb
    gcePersistentDisk:
      pdName: kube-mariadb
      fsType: ext4